#Created by Logan Bock, used for gateway's netplan configuration
network:
	version: 2
	renderer: networkd
	ethernets:
		enp0s3: #Logan Bock: network interface for client network
			dhcp4: no
			addresses: [192.128.8.100/24]
			nameservers:
				addresses: [8.8.8.8, 8.8.4.4]
		enp0s9: #Logan Bock: network interface for NatNetwork, dhcp4 for internet access
			dhcp4: yes
			nameservers:
				addresses: [8.8.8.8, 8.8.4.4]
		enp0s8: #Logan Bock: network interface for server network
			dhcp4: no
			addresses: [10.0.0.100/8]
			nameservers:
				addresses: [8.8.8.8, 8.8.4.4]
	