#Created by Logan Bock, used for server's netplan configuration
network:
	version: 2
	renderer: networkd
	ethernets:
		enp0s3: #Logan Bock: network interface for server network, gateway is set to gateway VM
			dhcp4: no
			addresses: [10.0.0.10/8]
			gateway4: 10.0.0.100
			nameservers:
				addresses: [8.8.8.8, 8.8.4.4]
	